title: "Peter Mitten"
description: "Sculpture"
url: "https://jedmitten.github.io"
baseurl: "/petermitten.com"

collections:
  works:
    output: true
    permalink: /works/:slug/

defaults:
  - scope:
      path: ""
      type: works
    values:
      layout: work
