title: "Peter Mitten"
description: "Sculpture"
url: "https://peter-mitten.com"
baseurl: ""

collections:
  works:
    output: true
    permalink: /works/:slug/

defaults:
  - scope:
      path: ""
      type: works
    values:
      layout: work
